import { Libre_Baskerville, Manrope } from 'next/font/google';
import './globals.css';
import { Nav, Footer } from '../components';

const manrope = Manrope({
  variable: '--font-manrope',
  subsets: ['latin'],
});

const libre = Libre_Baskerville({
  variable: '--font-libre_baskerville',
  subsets: ['latin'],
  weight: ['400'],
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${manrope.variable} ${libre.variable} antialiased overflow-x-clip`}>
        <main className="p-2.5 md:p-3 lg:p-4 bg-dark font-manrope">
          <Nav />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
